config/routes.rb
Rails.application.routes.draw do
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :hotels
   get '/users', to: 'users#index'
   get '/users/funk', to: 'users#function'
   #get '/cars', to: 'cars#index'
   post '/users', to: 'users#login'
   post '/users', to: 'users#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def ceao
        @stefanut = "Hei sunt stefanut si e prima mea app rails"
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    def index
        @cars = Car.all
        render :json =>@cars
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :position, :email)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @mancare = User.all
        #render json: @mancare
    end

    def function
        @users = User.all
        render :json =>@users
    end

    def login
        
        

        #in db
        #render params
        
        user = User.find_by(nickname: params[:name])
        if user != nil
            if user.password == params[:pass]
                flash.notice = 'Login with success!'
                redirect_to '/cars'
            else
                #byebug
                
                flash.alert = 'Credentials incorrect !'
                redirect_to '/users'
            end
    
        else
            #byebug
            flash.alert = 'User not found !'
            redirect_to '/users'
        end
    end

    def logout
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when :notice then "alert alert-success"
            when :alert then "alert alert-danger"
        end
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/index.html.erb
<%@cars.each do |car|%>
<%=car.marca%>
<%=car.model%>
<%end%>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.position %></td>
        <td><%= employee.email %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @employee.position %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>test</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key.to_sym).to_s %>">
         <a href="#" data-dismiss="alert" class="close">×</a>
         <%= value %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<head>
  <title>Bootstrap Example</title>

</head>


<body>
  <div class="container"> 
    <%= form_tag("/users", method: "post") do %>
      <%= label_tag(:q, "user:") %>
      <%= text_field_tag 'name' %>
      <%= label_tag(:q, "password:") %>
      <%= password_field_tag 'pass' %>
      <%= submit_tag("Log In") %>
    <% end %>
  <div>
</body>  